version: "3.3"

services:
  app:
    container_name: "app"
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/database_init.sql:/docker-entrypoint-initdb.d/init.sql:rw
