version: "3.3"

services:
  app:
    container_name: "app"
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - ./DataBase/database_init.sql:/docker-entrypoint-initdb.d/init.sql:rw
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 1000
